id: P000553
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:46:35.236392
source_metadata:
  id: bdr:W1KG25661
  title: བྲག་དཀར་སྤྲེལ་རྫོང་གི་གནས་བཤད།
  author: ''
  volumes:
    26ace4ca9fb1481b92b4d5d0fd4243d6:
      image_group_id: I1KG25663
      title: Volume 1 of brag dkar sprel rdzong gi gnas bshad/
      volume_number: 1
      total_pages: 51
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
